PlantFlagTool::makeFlag(): reload mesh resource
ros-visualization/visualization_tutorials pull request #67
Opened 2021-04-12 13:13 UTC by rhaschke

A Reset also resets the ResourceManager, such that the mesh resource
is not available anymore and createEntity() will fail.

Fixes ros-visualization/rviz#1618

@mabelzhang: Is there a particular reason that you branched off noetic-devel? I don't see any commits since then, which are noetic-only. In the past we use the same branch (kinetic-devel) for kinetic and melodic.
In any case this fix should be forward-ported to the noetic-devel branch as well.

2021-04-12 18:33 UTC, mabelzhang commented
`noetic-devel` was created here https://github.com/ros-visualization/visualization_tutorials/pull/60

2021-04-12 19:33 UTC, rhaschke commented
I see. Sorry, I missed this commit when skimming through the list. Please remember then to forward-port this PR after merging.

2025-04-23 18:07 UTC, sloretz requested changes
Thank you for the PR1

2025-04-23 18:07 UTC, sloretz commented on interactive_marker_tutorials/CHANGELOG.rst
> +0.10.5 (2020-05-13)
Please remove the `CHANGELOG.rst` and `package.xml` changes

2025-04-23 18:51 UTC, rhaschke commented
@sloretz I rebased my commit onto noetic-devel to get rid of conflicts.

2025-04-23 18:52 UTC, sloretz approved these changes

2025-04-23 19:22 UTC, merged